update-check: true
format: 'mm:ss'
# the expiration of the chest in seconds
expiration: 600
inventory-title: 'Death Chest'
spawn-hologram: true
# notification on death
notify:
  enabled: true
  message: |-
    &7You died. Your items were put into a chest which dispears after &c10 minutes&7!