name: Hangar Publish

on:
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish with Gradle to Hangar
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publishAllPublicationsToHangar
